trigger:
  branches:
    include:
      - main
      - develop
      - users/svelderrain/ci-cd  # Use forward slashes for branch names

name: $(Build.BuildID)

pool:
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'
  RelativePath: '$(Build.SourcesDirectory)'
  RelativePathScripts: '$(Build.SourcesDirectory)\pipeline\scripts'

stages:
- stage: BuildAndTest
  displayName: Build and Test LabVIEW Project
  jobs:
  - job: ExecuteScripts
    displayName: Execute Build.ps1 via PowerShell
    steps:
    - task: PowerShell@2
      displayName: 'Test and build the icon editor'
      inputs:
        filePath: '$(Build.SourcesDirectory)\pipeline\scripts\Build.ps1'
        arguments: >
          -RelativePath "$(RelativePath)"
          -RelativePathScripts "$(RelativePathScripts)"
        failOnStderr: true
