# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - "*"
pr:
  branches:
    include:
      - main
      
name: $(Build.BuildID)

pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'

stages:
- stage: Build_LVAddon_x86
  jobs:
  - template: pipeline\templates\Build_Icon_Editor_Packages.yml
    parameters:
     VIP_LVVersion: '2024'
     VIP_LVVersion_A: '24.3'
     SupportedBitness: '32'
     ApiVersion: 'v1'
     MinimumSupportedLVVersion: '2021'
     MinimumSupportedLVVersionLVAddon: '23.0'
     AddonName: 'niiconeditor64'
     RelativePath: $(Build.Repository.LocalPath)
     BuildSpec: 'Editor Packed Library'
     NIPB_Path: '$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\IconEditorDeployment_x86.pbs'
     Project: '$(Build.Repository.LocalPath)\lv_icon_editor.lvproj'
     PackedProjectLibraryVersion: '1.0.0.1'
     poolName: 'Default'
     projectDemands: 'iconeditor -equals true'
     
- stage: Build_LVAddon_x64
  jobs:
  - template: pipeline\templates\Build_Icon_Editor_Packages.yml
    parameters:
     VIP_LVVersion: '2024'
     VIP_LVVersion_A: '24.3 (64-bit)'
     SupportedBitness: '64'
     ApiVersion: 'v1'
     MinimumSupportedLVVersion: '2021'
     MinimumSupportedLVVersionLVAddon: '23.0'
     AddonName: 'niiconeditor64'
     RelativePath: $(Build.Repository.LocalPath)
     BuildSpec: 'Editor Packed Library'
     NIPB_Path: '$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\IconEditorDeployment_x64.pbs'
     Project: '$(Build.Repository.LocalPath)\lv_icon_editor.lvproj'
     PackedProjectLibraryVersion: '1.0.0.1'
     poolName: 'Default'
     projectDemands: 'iconeditor -equals true'