# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml      NIPB_Path: '$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\IconEditorDeployment_x86.pbs'  - job: ExecuteScripts

trigger:
  branches:
    include:
      - users/svelderr/ci-cd

name: $(Build.BuildID)

pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'
  RelativePath: '$(Build.Repository.LocalPath)'

stages:
- stage: BuildAndTest
  displayName: Build and Test LabVIEW Project
  jobs:
  - job: ExecuteScripts
    displayName: Execute PowerShell Scripts
    steps:
    - task: PowerShell@2
      displayName: Run Unit tests and build
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.Repository.LocalPath)\pipeline\scripts\Build.ps1'
        arguments: '-RelativePath "$(RelativePath)"'

    - script: echo "All scripts executed successfully."
      displayName: Completion Message
