trigger:
  branches:
    include:
      - main
      - develop
      - users/svelderrain/ci-cd  # Use forward slashes for branch names

name: $(Build.BuildID)

pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'
  RelativePath: '$(Build.Repository.LocalPath)'
  RelativePathScripts: '$(Build.Repository.LocalPath)\pipeline\scripts'

stages:
- stage: BuildAndTest
  displayName: Build and Test LabVIEW Project
  jobs:
  - job: ExecuteScripts
    displayName: Execute Build.ps1 via powershell
    steps:
    - script: |
        powershell -NoProfile -ExecutionPolicy Bypass -Command "& { . \"$(Build.Repository.LocalPath)\pipeline\scripts\Build.ps1\" -RelativePath \"$(RelativePath)\" -RelativePathScripts \"$(RelativePathScripts)\" }"
      displayName: Test and build the icon editor
