trigger:
  branches:
    include:
      - users/svelderr/ci-cd

name: $(Build.BuildID)

pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'
  RelativePath: '$(Build.Repository.LocalPath)'

stages:
- stage: BuildAndTest
  displayName: Build and Test LabVIEW Project
  jobs:
  - job: ExecuteScripts
    displayName: Execute Sequential PowerShell Scripts
    steps:
    - task: PowerShell@2
      displayName: Apply VIPC (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Applyvipc.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32 -RelativePath "$(RelativePath)" -VIPCPath "Tooling\deployment\Dependencies.vipc" -VIP_LVVersion "2021"

    - task: PowerShell@2
      displayName: Add Token to LabVIEW (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\AddTokenToLabVIEW.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32 -RelativePath "$(RelativePath)"

    - task: PowerShell@2
      displayName: Close LabVIEW (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Close_LabVIEW.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32

    - task: PowerShell@2
      displayName: Prepare LabVIEW Source (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Prepare_LabVIEW_source.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32 -RelativePath "$(RelativePath)" -LabVIEW_Project "lv_icon_editor" -Build_Spec "Editor Packed Library"

    - task: PowerShell@2
      displayName: Close LabVIEW After Preparation (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Close_LabVIEW.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32

    - task: PowerShell@2
      displayName: Run Unit Tests (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\RunUnitTests.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32 -RelativePath "$(RelativePath)"

    - task: PowerShell@2
      displayName: Build Packed Library (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Build_lvlibp.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32 -RelativePath "$(RelativePath)"

    - task: PowerShell@2
      displayName: Restore LabVIEW Source Setup (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\RestoreSetupLVSource.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 32 -RelativePath "$(RelativePath)" -LabVIEW_Project "lv_icon_editor" -Build_Spec "Editor Packed Library"

    - task: PowerShell@2
      displayName: Rename File (32-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Rename-File.ps1" -CurrentFilename "$(RelativePath)\resource\plugins\lv_icon.lvlibp" -NewFilename "lv_icon_x86.lvlibp"

    - task: PowerShell@2
      displayName: Apply VIPC (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Applyvipc.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64 -RelativePath "$(RelativePath)" -VIPCPath "Tooling\deployment\Dependencies.vipc" -VIP_LVVersion "2021"

    - task: PowerShell@2
      displayName: Add Token to LabVIEW (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\AddTokenToLabVIEW.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64 -RelativePath "$(RelativePath)"

    - task: PowerShell@2
      displayName: Close LabVIEW (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Close_LabVIEW.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64

    - task: PowerShell@2
      displayName: Prepare LabVIEW Source (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Prepare_LabVIEW_source.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64 -RelativePath "$(RelativePath)" -LabVIEW_Project "lv_icon_editor" -Build_Spec "Editor Packed Library"

    - task: PowerShell@2
      displayName: Close LabVIEW After Preparation (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Close_LabVIEW.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64

    - task: PowerShell@2
      displayName: Run Unit Tests (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\RunUnitTests.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64 -RelativePath "$(RelativePath)"

    - task: PowerShell@2
      displayName: Build Packed Library (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Build_lvlibp.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64 -RelativePath "$(RelativePath)"

    - task: PowerShell@2
      displayName: Restore LabVIEW Source Setup (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\RestoreSetupLVSource.ps1" -MinimumSupportedLVVersion 2021 -SupportedBitness 64 -RelativePath "$(RelativePath)" -LabVIEW_Project "lv_icon_editor" -Build_Spec "Editor Packed Library"

    - task: PowerShell@2
      displayName: Rename File (64-bit)
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\Rename-File.ps1" -CurrentFilename "$(RelativePath)\resource\plugins\lv_icon.lvlibp" -NewFilename "lv_icon_x64.lvlibp"

    - task: PowerShell@2
      displayName: Build VIP Package
      inputs:
        targetType: 'inline'
        script: |
          & "$(RelativePath)\pipeline\scripts\build_vip.ps1" -SupportedBitness 64 -RelativePath "$(RelativePath)" -VIPBPath "Tooling\deployment\NI Icon editor.vipb" -VIP_LVVersion 2021 -MinimumSupportedLVVersion 2021
