trigger:
  branches:
    include:
      - main
      - develop

name: $(Build.BuildID)

pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'
  RelativePath: '$(Build.Repository.LocalPath)'

stages:
- stage: BuildAndTest
  displayName: Build and Test LabVIEW Project
  jobs:
  - job: ExecuteScripts
    displayName: Execute Build.ps1 via powershell
    steps:
    - script: |
        powershell -NoProfile -ExecutionPolicy Bypass -File "$(Build.Repository.LocalPath)\pipeline\scripts\Build.ps1" -RelativePath "$(RelativePath)"
      displayName: Test and build the icon editor