name: Bug Report
description: Report a bug you've found
title: "[Bug]: "
labels: "bug"
body: 
- type: markdown
  attributes: 
    value: |
      Thanks for taking the time to fill out this bug report!
- type: dropdown
  id: version
  attributes:
    label: What version of the icon editor are you using?
    options:
      - The one the came with LabVIEW
      - Latest release from GitHub
      - Built from source
  validations:
    required: true
- type: textarea
  attributes:
    label: LabVIEW Version
    description: What LabVIEW version(s) have reported this issue?
    placeholder: e.g. LabVIEW 2021 SP1
  validations:
    required: true
- type: textarea
  attributes:
    label: OS
    description: What operating system are you using?
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Description / Summary
    description: A brief explanation of the bug and why it is problematic. Highlight the impact or severity if applicable.
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: A clear, step-by-step description of how someone else can trigger the bug. Number the steps and keep them precise and minimal.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: What you anticipated would happen if the software was functioning correctly. Helps distinguish the intended result from the bug.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: The actual outcome you observed, including error messages or undesired results. Highlight differences between the actual and expected behavior.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots / Logs / Error Messages (if applicable)
    description: Attach or paste screenshots, console logs, stack traces, or relevant error messages. This can be crucial for quickly identifying patterns or anomalies.
    placeholder: 
  validations:
    required: false
- type: textarea
  attributes:
    label: Possible Solution / Notes (optional, if you have ideas)
    description: If you’ve done any initial debugging or have a hypothesis about the cause, include it. Be clear that this is your best guess, not a definitive answer.
    placeholder: 
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context (optional)
    description: Anything else relevant to the issue - Links to related issues, workarounds you’ve tried, changes you recently made that might have introduced the bug, etc.
    placeholder: 
  validations:
    required: false

