name: "Upload VIP Artifact"
description: "Discovers the .vip file and uploads it as a GitHub Actions artifact."
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        clean: true
        persist-credentials: true

    - name: Discover .vip file
      id: find_vip
      shell: pwsh
      run: |
        $vipFile = Get-ChildItem -Path "builds/VI Package" -Filter "*.vip" -ErrorAction Stop |
                   Select-Object -First 1
        if (-not $vipFile) {
          Write-Host "No .vip file found!" -ForegroundColor Red
          exit 1
        }
        "vip_path=$($vipFile.FullName)" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

    - name: Upload .vip artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.version.outputs.VERSION }}
        path: ${{ steps.find_vip.outputs.vip_path }}