name: "Missing In Project"
description: >
  Executes MissinInProjectCLI.vi (bundled with this action) via g‑cli to
  verify referenced files in a LabVIEW project.  Uses an external PS1 script
  that follows the same pattern as Close_LabVIEW.ps1.

branding:
  icon: check-circle
  color: purple

inputs:
  lv-ver:
    description: "LabVIEW version (e.g. '2021')."
    required: true
  arch:
    description: "Bitness (32 or 64)."
    required: true
  project-file:
    description: >
      Full or relative path to the *.lvproj* to inspect.
      Defaults to `lv_icon.lvproj` in the repository root.
    required: false
    default: lv_icon.lvproj

outputs:
  passed:
    description: "True if VI reported success."
    value: ${{ steps.run_vi.outputs.passed }}
  missing-files:
    description: "Comma‑separated list of missing files."
    value: ${{ steps.run_vi.outputs.missing-files }}

runs:
  using: composite
  steps:

    # ------------------------------------------------------------
    # 1) Resolve the project‑file path
    # ------------------------------------------------------------
    - id: resolve
      name: Resolve project file
      shell: pwsh
      run: |
        $proj = '${{ inputs.project-file }}'
        if (-not [System.IO.Path]::IsPathRooted($proj)) {
          $proj = Join-Path $Env:GITHUB_WORKSPACE $proj
        }
        if (-not (Test-Path $proj)) {
          throw "Project file not found: $proj"
        }
        echo "projFile=$proj" >> $env:GITHUB_OUTPUT
        Write-Host "ℹ️  Using project file: $proj"

    # ------------------------------------------------------------
    # 2) Invoke the PowerShell helper (pattern matches Close_LabVIEW.ps1)
    # ------------------------------------------------------------
    - id: run_vi
      name: Execute VI via g‑cli (PS1 wrapper)
      shell: pwsh
      run: |
        & "$Env:GITHUB_ACTION_PATH\Invoke-MissingInProjectCLI.ps1" `
          -LVVersion  "${{ inputs.lv-ver }}" `
          -Arch       "${{ inputs.arch }}" `
          -ProjectFile "${{ steps.resolve.outputs.projFile }}"
