name: Initialize VIPB from JSON

on:
  workflow_dispatch:
    inputs:
      json_file:
        description: 'Input JSON file (relative to repo root)'
        required: true
        default: './Tooling/deployment/NI Icon editor LVAddon.json'
      company_name:
        description: 'Company Name (will overwrite .Library_General_Settings.Company_Name.__text)'
        required: true
        default: 'svelderrainruiz'
      author:
        description: 'Author (will overwrite .@Author)'
        required: true
        default: 'Sergio Velderrain'
      vipb_file:
        description: 'Output VIPB file (relative to repo root)'
        required: true
        default: './Tooling/deployment/NI Icon editor.vipb'

jobs:
  initialize-and-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show current values
        run: |
          echo "Company Name:"
          jq '.Library_General_Settings.Company_Name.__text' "${{ github.event.inputs.json_file }}" || true
          echo "Author:"
          jq '.["@Author"]' "${{ github.event.inputs.json_file }}" || true

      - name: Patch JSON (Company Name and Author)
        run: |
          jq '.Library_General_Settings.Company_Name.__text = "${{ github.event.inputs.company_name }}" |
              .["@Author"] = "${{ github.event.inputs.author }}"' \
              "${{ github.event.inputs.json_file }}" > modified.json

      - name: Show new values
        run: |
          echo "New Company Name:"
          jq '.Library_General_Settings.Company_Name.__text' modified.json || true
          echo "New Author:"
          jq '.["@Author"]' modified.json || true

      - name: JSON → VIPB
        uses: svelderrainruiz/json-vipb@v0.1.4
        with:
          args: json2vipb modified.json "${{ github.event.inputs.vipb_file }}"

      - uses: actions/upload-artifact@v4
        with:
          name: initialized-vipb
          path: |
            modified.json
            ${{ github.event.inputs.vipb_file }}
