name: JSON VIPB One-Step

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Conversion mode'
        required: true
        default: 'vipb2json'
        type: choice
        options:
          - vipb2json
          - json2vipb
      in_file:
        description: 'Input file (relative to repo root)'
        required: true
        default: './Tooling/deployment/NI Icon editor LVAddon.vipb'
      out_file:
        description: 'Output file (relative to repo root)'
        required: true
        default: './Tooling/deployment/NI Icon editor LVAddon.json'

jobs:
  json-vipb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print user input
        run: |
          echo "Mode: ${{ github.event.inputs.mode }}"
          echo "Input file: ${{ github.event.inputs.in_file }}"
          echo "Output file: ${{ github.event.inputs.out_file }}"
          ls -l "${{ github.event.inputs.in_file }}" || true

      - name: Run json-vipb action
        uses: svelderrainruiz/json-vipb@v0.1.4
        with:
          args: ${{ github.event.inputs.mode }} "${{ github.event.inputs.in_file }}" "${{ github.event.inputs.out_file }}"

      - name: Print output file (if JSON)
        if: ${{ github.event.inputs.mode == 'vipb2json' }}
        run: |
          if [ -f "${{ github.event.inputs.out_file }}" ]; then
            echo "-------------------"
            echo "${{ github.event.inputs.out_file }} contents:"
            if command -v jq > /dev/null; then
              jq . "${{ github.event.inputs.out_file }}"
            else
              cat "${{ github.event.inputs.out_file }}"
            fi
            echo "-------------------"
          else
            echo "Output file not found."
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: vipb-json-artifacts
          path: |
            ${{ github.event.inputs.in_file }}
            ${{ github.event.inputs.out_file }}
