name: VIPB → JSON

on:
  workflow_dispatch:
    inputs:
      vipb_path:
        description: 'Path to the .vipb file to convert (relative to repo root)'
        required: true
        default: './Tooling/deployment/NI Icon editor LVAddon.vipb'

jobs:
  roundtrip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print workspace and folder tree
        run: |
          echo "Working dir: $PWD"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Tree:"
          find . -type d | sort
          echo "Files:"
          find . -type f | sort

      # Print the file path actually being used
      - name: Echo VIPB input path
        run: |
          echo "VIPB input path: ${{ github.event.inputs.vipb_path }}"
          ls -l "${{ github.event.inputs.vipb_path }}"

      - name: VIPB → JSON
        uses: svelderrainruiz/json-vipb@v0.1.4
        with:
          args: vipb2json "${{ github.event.inputs.vipb_path }}" roundtrip.json

      - name: Print extracted JSON (pretty)
        run: |
          echo "-------------------"
          echo "Extracted roundtrip.json contents:"
          if command -v jq > /dev/null; then
            jq . roundtrip.json
          else
            cat roundtrip.json
          fi
          echo "-------------------"

      - uses: actions/upload-artifact@v4
        with:
          name: vipb-json-artifacts
          path: |
            ${{ github.event.inputs.vipb_path }}
            roundtrip.json
