name: Org Coding Hours

on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'Space-separated list of owner/repo names'
        required: true
      window_start:
        description: 'Optional start date YYYY-MM-DD'
        required: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: LabVIEW-Community-CI-CD/org-coding-hours-action@v2
      with:
        repos: ${{ github.event.inputs.repos }}
        window_start: ${{ github.event.inputs.window_start }}
