name: Post-merge Coding Hours

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-hours:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install git-hours
        run: npm install -g git-hours
      - name: Generate report
        run: git-hours --json > "reports/git-hours-$(date +%F).json"
      - name: Update README
        run: python scripts/update_readme_hours.py "reports/git-hours-$(date +%F).json"
      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "hours-bot"
          git config user.email "bot@users.noreply.github.com"
          git add README.md reports/git-hours-*.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "docs(readme): update coding hours [skip ci]"
            git push
          fi
