# .github/workflows/build-and-test.yml

name: Build and Test LabVIEW Project

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test the Icon Editor
    runs-on: [self-hosted, iconeditor]

    env:
      build_id: ${{ github.run_number }}
      build_revision: ${{ steps.get_revision.outputs.build_revision }}
      build_version: 1.0.${{ env.build_id }}.${{ env.build_revision }}
      RelativePath: ${{ vars.AgentWorkingFolder }}
      RelativePathScripts: ${{ vars.AgentWorkingFolder }}/pipeline/scripts

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Get Build Revision
      id: get_revision
      shell: bash
      run: |
        # Path to store the build revision counter
        COUNTER_FILE="${GITHUB_WORKSPACE}/.github/buildCounter.txt"
        echo "Counter file path: $COUNTER_FILE"

        # Initialize the counter file if it doesn't exist
        if [ ! -f "$COUNTER_FILE" ]; then
          echo "Counter file not found. Initializing to 1."
          echo "1" > "$COUNTER_FILE"
        fi

        # Read the current value
        build_revision=$(cat "$COUNTER_FILE")
        echo "Current build_revision: $build_revision"

        # Increment the counter
        new_build_revision=$((build_revision + 1))
        echo "New build_revision: $new_build_revision"

        # Save the new value back to the file
        echo "$new_build_revision" > "$COUNTER_FILE"

        # Set the output variable
        echo "::set-output name=build_revision::$build_revision"

        # For debugging
        ls -la "${GITHUB_WORKSPACE}/.github"
        cat "$COUNTER_FILE"

    - name: create-file
      shell: pwsh
      run: |
        echo hello > "$((Get-Date).ToString().Replace(":","_").Replace("/","_")).txt"; ls
