name: Run unit tests

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - hotfix/*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
      - feature/*
  workflow_dispatch:

jobs:
  run-labview-tests:
    # Matrix: test multiple OS, LabVIEW versions, and bitness
    strategy:
      matrix:
        os: [windows]        # Logical placeholders (we'll map them to specific self-hosted runners)
        lv-version: ["2021"]
        bitness: ["32","64"]
      fail-fast: false

    # Map your matrix OS to specific self-hosted runner labels
    # Example: a self-hosted Windows runner labeled "self-hosted-windows-lv"
    #          and a self-hosted Linux runner labeled "self-hosted-linux-lv"
    runs-on: ${{ matrix.os == 'windows' && 'self-hosted-windows-lv' || 'self-hosted-linux-lv' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        shell: pwsh
        working-directory: pipeline/scripts
        run: |
            $repoRoot = $env:GITHUB_WORKSPACE
            $scriptsFolder = Join-Path $repoRoot 'pipeline/scripts'
            .\RunUnitTests.ps1 -MinimumSupportedLVVersion ${{ matrix.lv-version }} -SupportedBitness ${{ matrix.bitness }}