name: End-to-End VIPB/JSON Seed and Patch

on:
  workflow_dispatch:

jobs:
  seed-vipb-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Compute file names and branch name using org/repo
      - name: Compute meta info
        id: meta
        run: |
          ORG="${{ github.repository_owner }}"
          REPO="${GITHUB_REPOSITORY##*/}"
          VIPB="$ORG-$REPO.vipb"
          JSONFILE="$ORG-$REPO.json"
          NOW=$(date +'%Y%m%d-%H%M%S')
          SHORTSHA=$(git rev-parse --short HEAD)
          BRANCH="seed/json-vipb/$ORG-$REPO/$NOW-$SHORTSHA"
          echo "vipb_file=$VIPB"      >> $GITHUB_OUTPUT
          echo "json_file=$JSONFILE"  >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH"  >> $GITHUB_OUTPUT

      # Step 1: Always create a fresh VIPB from the JSON
      - name: JSON → VIPB (fresh)
        run: |
          if [ ! -f "${{ steps.meta.outputs.json_file }}" ]; then
            echo "ERROR: Source JSON not found at repo root: ${{ steps.meta.outputs.json_file }}"
            exit 1
          fi
        # if you need to create a seed, uncomment below (but normally you want an existing JSON!)
        # echo '{"@Version":"2020.1", ...}' > "${{ steps.meta.outputs.json_file }}"
      - name: Convert JSON → VIPB
        uses: svelderrainruiz/json-vipb@v0.1.4
        with:
          args: json2vipb "${{ steps.meta.outputs.json_file }}" "${{ steps.meta.outputs.vipb_file }}"

      # Step 2: Create feature branch, push VIPB
      - name: Create and push branch with VIPB
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b "${{ steps.meta.outputs.branch_name }}"
          git add "${{ steps.meta.outputs.vipb_file }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Seed: VIPB generated from JSON"
          git push --set-upstream origin "${{ steps.meta.outputs.branch_name }}"

      # Step 3: Extract JSON from the new VIPB (on branch)
      - name: Extract JSON from pushed VIPB
        uses: svelderrainruiz/json-vipb@v0.1.4
        with:
          args: vipb2json "${{ steps.meta.outputs.vipb_file }}" "${{ steps.meta.outputs.json_file }}"

      # Step 4: Commit and push JSON to the branch
      - name: Commit and push extracted JSON
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add "${{ steps.meta.outputs.json_file }}"
          git commit -m "Extracted JSON from VIPB after initial push"
          git push

      # Step 5: Read the just-pushed JSON, patch Company Name to fork org name
      - name: Patch Company Name to repo owner (org)
        run: |
          jq '.Library_General_Settings.Company_Name.__text = "${{ github.repository_owner }}"' \
            "${{ steps.meta.outputs.json_file }}" > tmp.json
          mv tmp.json "${{ steps.meta.outputs.json_file }}"
          jq '.Library_General_Settings.Company_Name.__text' "${{ steps.meta.outputs.json_file }}" || true

      - name: Commit Company Name update to feature branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add "${{ steps.meta.outputs.json_file }}"
          git commit -m "Set Company Name to '${{ github.repository_owner }}' [seed automation]"
          git push

      # Optional: Print and upload result
      - name: Print JSON (pretty)
        run: jq . "${{ steps.meta.outputs.json_file }}" || cat "${{ steps.meta.outputs.json_file }}"
      - uses: actions/upload-artifact@v4
        with:
          name: final-json-and-vipb
          path: |
            ${{ steps.meta.outputs.vipb_file }}
            ${{ steps.meta.outputs.json_file }}
