name: Seed and Patch JSON-VIPB, Patch-First Style

on:
  workflow_dispatch:

jobs:
  patch-seed-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Compute canonical names and branch ---
      - name: Compute meta info
        id: meta
        run: |
          ORG="${{ github.repository_owner }}"
          REPO="${GITHUB_REPOSITORY##*/}"
          VIPB="$ORG-$REPO.vipb"
          JSONFILE="$ORG-$REPO.json"
          NOW=$(date +'%Y%m%d-%H%M%S')
          SHORTSHA=$(git rev-parse --short HEAD)
          BRANCH="seed/json-vipb/$ORG-$REPO/$NOW-$SHORTSHA"
          echo "vipb_file=$VIPB"      >> $GITHUB_OUTPUT
          echo "json_file=$JSONFILE"  >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH"  >> $GITHUB_OUTPUT

      # --- 1. Patch JSON with current repo owner as Company Name ---
      - name: Patch Company Name in JSON (pre-branch)
        run: |
          jq '.Library_General_Settings.Company_Name.__text = "${{ github.repository_owner }}"' \
            "${{ steps.meta.outputs.json_file }}" > tmp.json
          mv tmp.json "${{ steps.meta.outputs.json_file }}"
          jq '.Library_General_Settings.Company_Name.__text' "${{ steps.meta.outputs.json_file }}" || true

      # --- 2. Generate fresh VIPB from patched JSON ---
      - name: JSON → VIPB (fresh)
        uses: svelderrainruiz/json-vipb@v0.1.4
        with:
          args: json2vipb "${{ steps.meta.outputs.json_file }}" "${{ steps.meta.outputs.vipb_file }}"

      # --- 3. Create feature branch and commit both files together ---
      - name: Create and push branch with JSON and VIPB
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b "${{ steps.meta.outputs.branch_name }}"
          git add "${{ steps.meta.outputs.json_file }}" "${{ steps.meta.outputs.vipb_file }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Seed and patch: Set Company Name to '${{ github.repository_owner }}' and generate fresh VIPB"
          git push --set-upstream origin "${{ steps.meta.outputs.branch_name }}"

      # --- 4. Optional: Print and upload result for inspection ---
      - name: Print JSON (pretty)
        run: jq . "${{ steps.meta.outputs.json_file }}" || cat "${{ steps.meta.outputs.json_file }}"
      - uses: actions/upload-artifact@v4
        with:
          name: seeded-json-and-vipb
          path: |
            ${{ steps.meta.outputs.vipb_file }}
            ${{ steps.meta.outputs.json_file }}
