name: Quick VIPB‑JSON round‑trip test

on:
  workflow_dispatch:        # manual “Run workflow” button

jobs:
  roundtrip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------------- 1. JSON → VIPB ----------------
      - name: Build VIPB from JSON
        id: json_to_vipb
        uses: svelderrainruiz/json-vipb@v0.1.4   # make sure this tag has inputs declared
        with:
          mode: json2vipb
          in:  iconeditor.json
          out: iconeditor.vipb

      # ---------------- 2. VIPB → JSON ----------------
      - name: Extract JSON back
        id: vipb_to_json
        uses: svelderrainruiz/json-vipb@v0.1.3
        with:
          mode: vipb2json
          in:  iconeditor.vipb          # file just produced
          out: roundtrip.json

      # ---------------- 3. Hash compare ---------------
      - name: Compare hashes
        run: |
          orig=$(sha256sum iconeditor.json | cut -d ' ' -f1)
          new=$(sha256sum roundtrip.json | cut -d ' ' -f1)
          echo "Original JSON : $orig"
          echo "Round‑trip    : $new"
          if [ "$orig" != "$new" ]; then
            echo "::error::Hash mismatch – round‑trip not lossless"
            exit 1
          fi
          echo "Hashes match – conversion is lossless"

      # ---------------- 4. Upload artifacts -----------
      - uses: actions/upload-artifact@v4
        with:
          name: vipb‑roundtrip‑test
          path: |
            iconeditor.vipb
            iconeditor.json
            roundtrip.json
