# --------------------------------------------------------------------------
#  Coding‑hours report  – single‑view (no anonymity, no differentiation)
# --------------------------------------------------------------------------
name: Coding‑hours report

on:
  schedule:
    - cron: '0 0 * * 1'           # Monday 00:00 UTC
  workflow_dispatch:
    inputs:
      window_start:
        description: 'Analyse commits since YYYY‑MM‑DD (optional)'
        required: false
      window_end:
        description: 'Analyse commits up to YYYY‑MM‑DD (optional)'
        required: false

# --------------------------------------------------------------------------
concurrency:
  group: coding-hours-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write        # for artefact DELETE (409 fix)

env:
  GO_VERSION: '1.24'
  GITHOURS_VERSION: 'v0.1.2'

jobs:
  report:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    # --------------------------------------------------------------------
    # 1️⃣  Checkout full history
    # --------------------------------------------------------------------
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # --------------------------------------------------------------------
    # 2️⃣  Setup Go & module cache
    # --------------------------------------------------------------------
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    # --------------------------------------------------------------------
    # 3️⃣  Cache compiled git‑hours
    # --------------------------------------------------------------------
    - name: Cache git‑hours binary
      id: cache-githours
      uses: actions/cache@v4
      with:
        path: ~/go/bin/git-hours
        key: git-hours-${{ env.GO_VERSION }}-${{ env.GITHOURS_VERSION }}

    - name: Install git‑hours (patched go.mod)
      if: steps.cache-githours.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 --branch $GITHOURS_VERSION https://github.com/trinhminhtriet/git-hours.git /tmp/git-hours
        sed -i 's/go 1\.24\.1/go 1.24/' /tmp/git-hours/go.mod
        (cd /tmp/git-hours && go install .)

    # --------------------------------------------------------------------
    # 4️⃣  Compute reporting window
    # --------------------------------------------------------------------
    - name: Compute date window
      id: dates
      run: |
        since="${{ github.event.inputs.window_start }}"
        until="${{ github.event.inputs.window_end }}"
        [[ -z "$since" ]] && since=$(date -u -d "last monday" +%F)
        [[ -z "$until" ]] && until=$(date -u +%F)
        echo "since=$since" >> "$GITHUB_OUTPUT"
        echo "until=$until" >> "$GITHUB_OUTPUT"

    # --------------------------------------------------------------------
    # 5️⃣  Generate raw git‑hours report
    # --------------------------------------------------------------------
    - name: Generate git‑hours report
      run: |
        git-hours -since "${{ steps.dates.outputs.since }}" \
                  -until "${{ steps.dates.outputs.until }}" > git-hours.txt

    - name: Add raw report to summary
      run: |
        {
          echo "## ⏱ Coding‑hours report"
          echo "_${{ steps.dates.outputs.since }} → ${{ steps.dates.outputs.until }}_"
          echo ''
          echo '```text'
          cat git-hours.txt
          echo '```'
        } >> "$GITHUB_STEP_SUMMARY"

    # --------------------------------------------------------------------
    # 6️⃣  Upload raw report  (pre‑delete to avoid 409)
    # --------------------------------------------------------------------
    - name: Delete stale git‑hours artefact
      if: always()
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ART="git-hours-${{ github.run_id }}"
        ids=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
              --jq ".artifacts[] | select(.name==\"$ART\") | .id")
        for id in $ids; do
          echo "Deleting artefact id=$id → $ART"
          gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$id
        done

    - uses: actions/upload-artifact@v4
      with:
        name: git-hours-${{ github.run_id }}
        path: git-hours.txt
        retention-days: 30

    # --------------------------------------------------------------------
    # 7️⃣  Python visualisation (all contributors together)
    # --------------------------------------------------------------------
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install plotting libraries
      run: pip install --disable-pip-version-check pandas matplotlib

    - name: Build graphs
      run: |
        python - <<'PY'
        import base64, io, json, os, re, pathlib, datetime as dt
        import pandas as pd, matplotlib.pyplot as plt, collections

        TXT = pathlib.Path('git-hours.txt').read_text()

        # ---------- parse git-hours output ----------
        def parse(raw):
            try:
                data = json.loads(raw)
                return [(k, v['hours']) for k, v in data.items() if k.lower() != 'total']
            except json.JSONDecodeError:
                pat = re.compile(r'^\s*(.*?)\s+(\d+(?:\.\d+)?)\s*h', re.I)
                return [(m.group(1).strip(), float(m.group(2)))
                        for m in map(pat.match, raw.splitlines()) if m]

        rows = parse(TXT)
        if not rows:
            print('::warning::Unable to parse git-hours.txt'); exit(0)
        df_now = pd.DataFrame(rows, columns=['author', 'hours'])

        # ---------- bar chart (current window) ----------
        df_now.sort_values('hours', inplace=True)
        fig_bar, ax = plt.subplots(figsize=(6, max(2, .35*len(df_now))))
        ax.barh(df_now['author'], df_now['hours'])
        ax.set_xlabel('Hours'); ax.set_title('Hours per contributor')
        plt.tight_layout()

        # ---------- stacked ISO‑week trend (last 8) ----------
        def wk(date_str):
            iso = dt.date.fromisoformat(date_str).isocalendar()
            return f"{iso.year}-W{iso.week:02d}"

        def parse_file(fp):
            return {a: h for a, h in parse(fp.read_text())}

        hist = collections.defaultdict(lambda: collections.Counter())
        for f in pathlib.Path('reports').glob('git-hours-*_to_*.txt'):
            end = f.stem.split('_to_')[-1]
            hist[wk(end)].update(parse_file(f))

        current_week = wk('${{ steps.dates.outputs.until }}')
        hist[current_week].update(df_now.set_index('author')['hours'].to_dict())

        weeks = sorted(hist.keys())[-8:]
        fig_trend = None
        if weeks:
            pivot = pd.DataFrame([{**{'week': w}, **hist[w]} for w in weeks]).fillna(0)
            pivot.set_index('week', inplace=True)
            fig_trend, ax2 = plt.subplots(figsize=(6,3))
            labels = pivot.columns
            ax2.stackplot(pivot.index, *[pivot[c] for c in labels], labels=labels)
            ax2.legend(fontsize=6, loc='upper left', bbox_to_anchor=(1,1))
            ax2.set_ylabel('Hours')
            ax2.set_title('Weekly coding‑hours (last 8 ISO weeks)')
            plt.xticks(rotation=45, ha='right'); plt.tight_layout()

        # ---------- embed in summary ----------
        def b64(fig):
            buf = io.BytesIO(); fig.savefig(buf, format='png', dpi=140)
            return base64.b64encode(buf.getvalue()).decode()

        summary = pathlib.Path(os.environ['GITHUB_STEP_SUMMARY'])
        with summary.open('a') as s:
            s.write('## 📊 Coding‑hours visual summary\n\n')
            s.write(f'<img alt="bar" src="data:image/png;base64,{b64(fig_bar)}"/>\n\n')
            if fig_trend:
                s.write(f'<img alt="trend" src="data:image/png;base64,{b64(fig_trend)}"/>\n')
        PY

    # --------------------------------------------------------------------
    # 8️⃣  Optional: commit reports to metrics branch
    # --------------------------------------------------------------------
    - name: Commit to metrics branch
      if: github.ref_name == 'main'
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}  # PAT with repo write
      run: |
        if [ -z "$GH_TOKEN" ]; then
          echo "GH_PAT secret not set — skipping metrics commit"
          exit 0
        fi
        git config --global user.name  "git‑hours bot"
        git config --global user.email "bot@github.com"
        git fetch origin metrics || true
        git switch -C metrics origin/metrics || git switch -C metrics
        mkdir -p reports
        cp git-hours.txt "reports/git-hours-${{ steps.dates.outputs.since }}_to_${{ steps.dates.outputs.until }}.txt"
        git add reports
        git commit -m "chore(metrics): coding hours ${{ steps.dates.outputs.since }}→${{ steps.dates.outputs.until }}" || echo "No changes"
        git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}" HEAD:metrics
