name: VIPB ➜ JSON smoke test           # workflow title (optional)

on:                                    # ← required root key
  workflow_dispatch:                   # manual “Run workflow” button in UI

jobs:                                  # ← required root key
  vipb-to-json:
    runs-on: ubuntu-latest             # GitHub‑hosted Linux runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- convert VIPB → JSON -------------------------------
      - name: Extract JSON from VIPB
        id: vipb2json
        uses: svelderrainruiz/json-vipb@v0.1.4   # tag without custom inputs
        with:
          args: vipb2json iconeditor.vipb iconeditor.extracted.json

      # ---------- upload artifact for inspection --------------------
      - name: Upload extracted JSON
        uses: actions/upload-artifact@v4
        with:
          name: vipb-json-output
          path: iconeditor.extracted.json
